# HAL config
option( HAL_MODULE_ENABLED "Enable HAL module " ON)
option( HAL_CORTEX_MODULE_ENABLED "Enable HAL CORTEX" ON )
option( HAL_RCC_MODULE_ENABLED "Enable HAL RCC" ON )
option( HAL_GPIO_MODULE_ENABLED "Enable HAL GPIO" ON )
option( HAL_I2C_MODULE_ENABLED "Enable HAL I2C" ON )
option( HAL_ADC_MODULE_ENABLED "Enable HAL ADC" OFF )
option( HAL_SPI_MODULE_ENABLED "Enable HAL SPI" OFF )
option( HAL_UART_MODULE_ENABLED "Enable HAL UART" ON )
option( HAL_USART_MODULE_ENABLED "Enable HAL USART" ON )
option( HAL_RTC_MODULE_ENABLED "Enable HAL RTC" ON )    
option( HAL_FLASH_MODULE_ENABLED "Enable HAL FLASH" ON )
option( HAL_RNG_MODULE_ENABLED "Enable HAL RNG" OFF )
option( HAL_CRC_MODULE_ENABLED "Enable HAL CRC" OFF )
option( HAL_PWR_MODULE_ENABLED "Enable HAL PWR" ON )
option( HAL_FIREWALL_MODULE_ENABLED "Enable HAL FIREWALL" OFF )
option( HAL_TIM_MODULE_ENABLED "Enable HAL TIM" ON )
option( HAL_LPTIM_MODULE_ENABLED "Enable HAL LPTIM" OFF )
option( HAL_IWDG_MODULE_ENABLED "Enable HAL IWDG" OFF )
option( HAL_WWDG_MODULE_ENABLED "Enable HAL WWDG" OFF )
option( HAL_SRAM_MODULE_ENABLED "Enable HAL SRAM" ON )    
option( HAL_EXTI_MODULE_ENABLED "Enable HAL EXTI" ON )
option( HAL_DMA_MODULE_ENABLED "Enable HAL DMA" ON )
#### Callback config
option( USE_HAL_ADC_REGISTER_CALLBACKS "Enable Register callback for ADC" OFF )
option( USE_HAL_I2C_REGISTER_CALLBACKS "Enable Register callback for I2C" OFF )
option( USE_HAL_LPTIM_REGISTER_CALLBACKS "Enable Register callback for LPTIM" OFF )
option( USE_HAL_RNG_REGISTER_CALLBACKS "Enable Register callback for RNG" OFF )
option( USE_HAL_RTC_REGISTER_CALLBACKS "Enable Register callback for RTC" OFF )
option( USE_HAL_SPI_REGISTER_CALLBACKS "Enable Register callback for SPI" OFF )
option( USE_HAL_TIM_REGISTER_CALLBACKS "Enable Register callback for TIM" OFF )
option( USE_HAL_UART_REGISTER_CALLBACKS "Enable Register callback for UART" OFF )
option( USE_HAL_USART_REGISTER_CALLBACKS "Enable Register callback for USART" OFF )
option( USE_HAL_WWDG_REGISTER_CALLBACKS "Enable Register callback for WWDG" OFF )
### LL config
option( USE_FULL_LL_DRIVER "Enable LL full driver" ON )
### System Configuration
set( HSE_VALUE "8000000U" )
set( HSE_STARTUP_TIMEOUT "100U" )
set( MSI_VALUE "4000000U" )
set( LSE_VALUE "32768U" )
set( LSE_STARTUP_TIMEOUT "5000U" )

set( VDD_VALUE "2500U" )
set( TICK_INT_PRIORITY "0U")
set( USE_RTOS "0U")    
set( PREFETCH_ENABLE "0U")
set( INSTRUCTION_CACHE_ENABLE "1U")
set( DATA_CACHE_ENABLE "1U")
set( USE_FULL_ASSERT "0U")

set( USE_SPI_CRC "0U")